--- #YAML:1.0
name: HOP-Lexer
version: 0.03
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: '"Higher Order Perl" Lexer'
license: open_source
generated_by: Module::Build version 0.2704, without YAML.pm
